# Generated by Django 5.2 on 2025-04-08 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanrequest',
            name='amount',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='dni',
            field=models.PositiveIntegerField(max_length=16),
        ),
    ]
