# Generated by Django 5.2 on 2025-04-08 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0002_alter_loanrequest_amount_alter_loanrequest_dni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanrequest',
            name='dni',
            field=models.PositiveIntegerField(),
        ),
    ]
